#include "dk1/player_terrain_runtime.h"
#include <limits.h>
#include <stdlib.h>
#include <string.h>
static bool best_support(const Dk1PlayerTerrainRuntime*r,uint16_t x,int32_t target,int32_t below,int32_t above,Dk1TerrainSample*out){static const int16_t dx[3]={-7,0,7};Dk1TerrainSample s,best={0};int32_t best_delta=INT32_MAX;size_t i,row;if(!r||!r->ready||!out)return false;for(i=0;i<3;i++){int32_t sx=(int32_t)x+dx[i];if(sx<0)continue;for(row=0;row<DK1_TERRAIN_ROWS;row++){int32_t cy=(int32_t)row*32;int32_t d;if(!dk1_rom_terrain_sample_cell(&r->view,sx,cy,&s))continue;if(s.floor_y<target-below||s.floor_y>target+above)continue;d=abs((int)(s.floor_y-target));if(d<best_delta||(d==best_delta&&s.floor_y>best.floor_y)){best=s;best_delta=d;}}}if(!best.hit)return false;*out=best;return true;}
bool dk1_player_terrain_init(Dk1PlayerTerrainRuntime*r,const Dk1RomImage*rom,Dk1LevelTerrainConfig cfg,uint32_t max_x){size_t cols;if(!r||!rom)return false;memset(r,0,sizeof(*r));cols=(size_t)((max_x+96u)/32u+2u);if(!cols)cols=1u;if(!dk1_terrain_shape_flags_from_rom(rom,r->shape_flags)||!dk1_rom_terrain_view_init(&r->view,rom,cfg,cols,r->shape_flags))return false;r->column_count=cols;r->foot_offset=16;r->half_width=7;r->ready=true;return true;}
bool dk1_player_terrain_place(Dk1PlayerTerrainRuntime*r,Dk1PlayerPreviewRuntime*p,uint16_t viewport_height,uint16_t*camera_y){Dk1TerrainSample s;int32_t target,center,desired,max_camera;if(!r||!p||!r->ready)return false;target=(int32_t)p->motion.world_y-r->foot_offset;if(!best_support(r,p->motion.world_x,target,512,512,&s)){r->misses++;return false;}center=s.floor_y+r->foot_offset;p->motion.world_y=(int16_t)center;p->motion.velocity_y=0;p->motion.subpixel_y=0;p->floor_y=(int16_t)center;p->floor_attributes=s.attributes;p->airborne=false;r->support=s;r->last_attributes=s.attributes;r->resolved_contacts++;if(camera_y){desired=512-center-(int32_t)viewport_height/2;max_camera=512-(int32_t)viewport_height;if(max_camera<0)max_camera=0;if(desired<0)desired=0;if(desired>max_camera)desired=max_camera;*camera_y=(uint16_t)desired;}return true;}
void dk1_player_terrain_resolve(Dk1PlayerTerrainRuntime*r,Dk1PlayerPreviewRuntime*p,int16_t old_world_y){Dk1TerrainSample s;int32_t old_foot,new_foot,stand;bool was_airborne,can_snap=false;if(!r||!p||!r->ready)return;old_foot=(int32_t)old_world_y-r->foot_offset;new_foot=(int32_t)p->motion.world_y-r->foot_offset;was_airborne=p->airborne;if(best_support(r,p->motion.world_x,new_foot,40,24,&s)){if(p->motion.velocity_y<=0){if(was_airborne)can_snap=s.floor_y>=new_foot-6&&s.floor_y<=old_foot+10;else can_snap=abs((int)(s.floor_y-new_foot))<=14;}if(can_snap){stand=s.floor_y+r->foot_offset;p->motion.world_y=(int16_t)stand;p->motion.subpixel_y=0;p->motion.velocity_y=0;p->floor_y=(int16_t)stand;p->floor_attributes=s.attributes;p->airborne=false;if(was_airborne)p->landings++;r->support=s;r->last_attributes=s.attributes;r->resolved_contacts++;return;}}p->airborne=true;r->misses++;}
void dk1_player_terrain_step(Dk1PlayerTerrainRuntime*r,Dk1PlayerPreviewRuntime*p,uint16_t held,uint16_t pressed){int16_t old;if(!r||!p||!r->ready){dk1_player_preview_step(p,held,pressed);return;}old=p->motion.world_y;dk1_player_preview_advance(p,held,pressed);dk1_player_terrain_resolve(r,p,old);}
